site_name: MIPP Documentation
site_url: https://aff3ct.github.io/mipp/
theme:
  name: material
  logo: assets/images/mipp_ico.jpg
  favicon: assets/images/mipp_ico_circle.png
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    # 1. Automatic mode (adapts to system preferences by default)
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # 2. Forced light mode
    - scheme: default
      primary: white
      accent: cyan
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # 3. Forced dark mode
    - scheme: slate
      primary: slate
      accent: cyan
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to system preference

  language: en

repo_url: https://github.com/aff3ct/mipp/

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets :
      auto_append:
        - docs/includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr

plugins: 
  - search
  - awesome-pages

extra_css:
  - css/extra.css
  - assets/explorer/explorer.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/toc-toggle.js
  - assets/explorer/explorer.js
