#!/usr/bin/env python3

from jinja2 import Template, StrictUndefined
import json
import copy
import sys
sys.path.insert(1, '.')

from tools import *
from headers_def import *
from implem_rvv import *
from implem_emu_rvv import *
from generic_emu import *
from c_generator import gen_c_functions_rvv, gen_c_missing_functions_lmul

from include_gen import IncludeManager



#templates used in fix_reductions to change the code between lmul=1 and lmul>1 for hadd,hmin,hmax
ir_reduction_fix = {
    "extract_scalar": "{{isa_dt_par.to_ptr}} scalar = {{isa.prefix}}_vmv_x_s_{{isa_dt_par.data_ext}}_{{isa_dt_par.reg_dt_ext}}(tmp);",
    "insert_scalar": "%r<tp>% ret; ret.r = {{isa.prefix}}_vmv_s_x_{{isa_dt_par.data_ext}}(scalar, %N<tp>%);",
    "extract_float": "{{isa_dt_par.to_ptr}} scalar = {{isa.prefix}}_vfmv_f_s_{{isa_dt_par.data_ext}}_{{isa_dt_par.reg_dt_ext}}(tmp);",
    "insert_float": "%r<tp>% ret; ret.r = {{isa.prefix}}_vfmv_s_f_{{isa_dt_par.data_ext}}(scalar, %N<tp>%);",
}

#reductions are annoying in RVV. 
#bc their intrinsics is 
#[v[type]m1_t] __riscv_vred[op]_[]_[type][lmul]_[type]m1
#so they return m1 AND take m1 as arg2. 
#I'll separate reductions between m1 and m>1
#and change the ones with m>1 to return a vector 
#of the correct lmul

#returns a dict with the converted ir to insert back 
#when calling gen_c_functions
def fix_reductions(isa, isa_lmul1, funcs, implems_dict, lmul):
    """
    Very hacky and unstable fix to generate the correct code 
    for hmax/hmin/hadd with lmul >1. 
    
    The function returns a dict with the converted ir for every 
    instruction/type i.e smtg like : {"hadd" : {"uint32" : "code", "int8" : "code"}, "hmin" {...}}
    to replace the code generated by gen_c_functions.
    
    WATCH OUT: THIS FUNCTION IS HACKY. 
    IF THE TEMPLATES OF HADD/HMIN/HMAX CHANGE. IT **WILL** BREAK.
    """
    ret = {}
    if lmul == "0" or lmul == 0 or lmul == "1" or lmul == 1:
        return {}
    reductions = mipp_funcs_concepts["reduction"]
    for f in reductions:
        if f == "hmul" or f == "testz" or f == "testz_2" or f == "hadd_to_scal":
            continue
        ret[f] = {}
        if f in implems_dict:
            for ff in implems_dict[f]:
                ir = ff["template"]["code"]
                line1_ir = ir.splitlines()[1]
                line2_ir = ir.splitlines()[2]
                
                for dt in ff["datatypes"]:
                    dt_par = dt.split(',')[0]
                    dt_ret = dt.split(',')[0]
                    dt_key = dt_par + "," + dt_ret
                    template = Template(line1_ir, undefined=StrictUndefined)
                    #line 1 -> rendered with isa_lmul1 and lmul = 1
                    pre_rendering = template.render(isa=isa_lmul1, instr_name=f, dt_par=datatypes[dt_par], dt_ret=datatypes[dt_ret], isa_dt_par=isa_lmul1["datatypes"][dt_par], isa_dt_ret=isa_lmul1["datatypes"][dt_ret], cstdint_ret=datatypes[dt_ret]["cstd"])
                    ph_ret = parse_placeholders(pre_rendering, isa_lmul1, funcs, f, dt_par, dt_ret,lmul="1")
                    ret[f][dt] = ph_ret["converted_ir"]
                    #line 2 -> rendered with isa and lmul = current lmul. This line is not changed.
                    template = Template(line2_ir, undefined=StrictUndefined)
                    
                    pre_rendering = template.render(isa=isa, instr_name=ff["instr_name"], dt_par=datatypes[dt_par], dt_ret=datatypes[dt_ret], isa_dt_par=isa["datatypes"][dt_par], isa_dt_ret=isa["datatypes"][dt_ret], cstdint_ret=datatypes[dt_ret]["cstd"], lmul=lmul)
                    #line 2 is not changed but we need to render it with the correct lmul for the next step
                    ph_ret = parse_placeholders(pre_rendering, isa, funcs, f, dt_par, dt_ret,lmul=lmul)
                    ret[f][dt] = ret[f][dt] + "\n" + ph_ret["converted_ir"]
                    
                    #line 3 -> r0.r = tmp. This line is changed to extract/insert
                    # extract lmul=1 isa=isa_lmul1 of the correct type and lmul and then rendered
                    if dt in all_float : 
                        template = Template(ir_reduction_fix["extract_float"], undefined=StrictUndefined)
                    else:
                        template = Template(ir_reduction_fix["extract_scalar"], undefined=StrictUndefined)
                    pre_rendering = template.render(isa=isa_lmul1, instr_name=f, dt_par=datatypes[dt_par], dt_ret=datatypes[dt_ret], isa_dt_par=isa_lmul1["datatypes"][dt_par], isa_dt_ret=isa_lmul1["datatypes"][dt_ret], cstdint_ret=datatypes[dt_ret]["cstd"], lmul="1")
                    ph_ret = parse_placeholders(pre_rendering, isa_lmul1, funcs, f, dt_par, dt_ret,lmul="1")
                    ret[f][dt] = ret[f][dt] + "\n" + ph_ret["converted_ir"]
                    
                    #insert lmul= current lmul isa=isa of the correct type and lmul and then rendered
                    if dt in all_float : 
                        template = Template(ir_reduction_fix["insert_float"], undefined=StrictUndefined)
                    else:
                        template = Template(ir_reduction_fix["insert_scalar"], undefined=StrictUndefined)
                    pre_rendering = template.render(isa=isa, instr_name=f, dt_par=datatypes[dt_par], dt_ret=datatypes[dt_ret], isa_dt_par=isa["datatypes"][dt_par], isa_dt_ret=isa["datatypes"][dt_ret], cstdint_ret=datatypes[dt_ret]["cstd"], lmul=lmul)
                    ph_ret = parse_placeholders(pre_rendering, isa, funcs, f, dt_par, dt_ret,lmul=lmul)
                    ret[f][dt] = ret[f][dt] + "\n" + ph_ret["converted_ir"]
                    
                    #line 4 -> return ret. This line is not changed.
                    ret[f][dt] = ret[f][dt] + "\nreturn ret;"
    return ret

def seen_lmul(funcs, f, dt_key, lmul):
    if "implem_status" in funcs[f] :
        if "lmul" in funcs[f]["implem_status"] :
            if (lmul,dt_key) in funcs[f]["implem_status"]["lmul"]:
                return True
    return False

def gen_c_defines_rvv_ls(file, isa_name, rvv_size):
    print("#define MIPP_" + isa_name.upper() + "_RVD_SIZE_BIT " + str(rvv_size), file=file)
    print("#define MIPP_" + isa_name.upper() + "_RVD_SIZE_BYTE " + str(rvv_size + "/ 8"), file=file)
    template = """#define MIPP_RVV_N_{{type_category_upper}}{{n_bits}} {{type_size}}"""
    j2_template = Template(template, undefined=StrictUndefined)
    for dt in isa_rvv["datatypes"]:
        n_bits=datatypes[dt]["n_bits"]
        print(j2_template.render(rvv_size=rvv_size, n_bits=n_bits, type_size = str(f'{rvv_size}/{n_bits}'), type_category_upper=datatypes[dt]["category"].upper()), file=file)
    
    for lmul in all_lmul:
        for dt in isa_rvv["datatypes"]:
            n_bits=datatypes[dt]["n_bits"]
            type_size = f'{rvv_size}/{n_bits}*{lmul}'
            template = """#define MIPP_RVV_N_{{type_category_upper}}{{n_bits}}_M{{lmul}} {{type_size}}"""
            j2_template = Template(template, undefined=StrictUndefined)
            print(j2_template.render(rvv_size=rvv_size, n_bits=n_bits, type_size = type_size, type_category_upper=datatypes[dt]["category"].upper(), lmul=lmul), file=file)

def gen_c_structures_rvv_ls(file, rvv_size):
    
    #rvd type generation
    template = """typedef {{ isa_datatype.reg }} fixed_m{lmul}_{{isa_datatype.to_ptr}} __attribute__((riscv_rvv_vector_bits({{ rvv_size }}*{lmul})));"""
    j2_template = Template(template, undefined=StrictUndefined)
    for lmul in all_lmul:
        for dt in isa_rvv["datatypes"]:
            template = j2_template.render(isa_datatype=isa_rvv["datatypes"][dt],rvv_size=rvv_size)
            template = template.format(lmul = lmul)#lmul hack;)
            print(template, file=file)
     
    #rvm type generation
    template = """typedef {{isa_datatype.msk}} fixed_m{lmul}_bool{n_bits}_t __attribute__((riscv_rvv_vector_bits({{ rvv_size }}*{lmul}/(8*sizeof({{isa_datatype.to_ptr}})))));"""
    j2_template = Template(template, undefined=StrictUndefined)
    dt_list = {uint64, uint32, uint16, uint8}
    for lmul in all_lmul:
        for dt in dt_list:
            n_bits = datatypes[dt]["n_bits"]
            nb_elem = f'{rvv_size} / {n_bits}'  	
            tmp = j2_template.render(rvv_size=rvv_size, isa_datatype=isa_rvv["datatypes"][dt], nb_elem=nb_elem)  
            tmp = tmp.format(lmul = lmul, eew_emul = str(int(n_bits/(lmul))), n_bits = str(n_bits))#lmul hack;)   
            print(tmp, file=file)
        print("\n", file=file)

    #rvd struct generation
    template = """typedef struct { fixed_m{lmul}_{{isa_datatype.to_ptr }} r; } rvd_{{ isa.name }}_{{ datatype.category }}{{ datatype.n_bits }}_m{lmul}_t;"""

    for lmul in all_lmul:
        for dt in isa_rvv["datatypes"]:
            n_bits = datatypes[dt]["n_bits"]
            nb_elem = f'{rvv_size} / {n_bits} * {lmul}'
            tmp = template.replace("{lmul}", str(lmul))
            j2_template = Template(tmp, undefined=StrictUndefined)
            print(j2_template.render(isa=isa_rvv,rvv_size=rvv_size,isa_datatype=isa_rvv["datatypes"][dt], datatype=datatypes[dt], lmul=lmul), file=file)

    #typedef of rvd m1 to no suffix
    template = """typedef rvd_{{ isa.name }}_{{ datatype.category }}{{ datatype.n_bits }}_m1_t rvd_{{ isa.name }}_{{ datatype.category }}{{ datatype.n_bits }}_t;"""
    for dt in isa_rvv["datatypes"]:
        n_bits = datatypes[dt]["n_bits"]
        nb_elem = f'{rvv_size} / {n_bits}'
        tmp = template.replace("_m{lmul}", "")
        j2_template = Template(tmp, undefined=StrictUndefined)
        print(j2_template.render(isa=isa_rvv,rvv_size=rvv_size,isa_datatype=isa_rvv["datatypes"][dt], datatype=datatypes[dt], lmul=""), file=file)
    
    #rvm struct generation
    template = """typedef struct { fixed_m{lmul}_bool{n_bits}_t m; } rvm_{{ isa.name }}_{{ datatype.category }}{{ datatype.n_bits }}_m{lmul}_t;"""
    j2_template = Template(template, undefined=StrictUndefined)
       
    for lmul in all_lmul:
        for dt in isa_rvv["datatypes"]:
            n_bits = datatypes[dt]["n_bits"]
            nb_elem = f'{rvv_size} / {n_bits} * {lmul}'
            tmp = template.replace("{lmul}", str(lmul))
            tmp = tmp.replace("{n_bits}", str(n_bits))
            j2_template = Template(tmp, undefined=StrictUndefined)
            print(j2_template.render(isa=isa_rvv,rvv_size=rvv_size,isa_datatype=isa_rvv["datatypes"][dt], datatype=datatypes[dt], lmul=lmul), file=file)
    
    template = """typedef rvm_{{ isa.name }}_{{ datatype.category }}{{ datatype.n_bits }}_m1_t rvm_{{ isa.name }}_{{ datatype.category }}{{ datatype.n_bits }}_t;"""
    for dt in isa_rvv["datatypes"]:
        n_bits = datatypes[dt]["n_bits"]
        nb_elem = f'{rvv_size} / {n_bits}'
        tmp = template.replace("_m{lmul}", "")
        j2_template = Template(tmp, undefined=StrictUndefined)
        print(j2_template.render(isa=isa_rvv,rvv_size=rvv_size,isa_datatype=isa_rvv["datatypes"][dt], datatype=datatypes[dt], lmul=""), file=file)
#taken from gen_mipp_avx.py (changed)

def resolve_lmul_in_isa(isa, lmul):
    if lmul == "0" or lmul == 0:
        lmul = "1"
    resolved_isa = copy.deepcopy(isa)
    for dt in resolved_isa["datatypes"]:
        for key in resolved_isa["datatypes"][dt]:
            if "{lmul}" in resolved_isa["datatypes"][dt][key]:
                resolved_isa["datatypes"][dt][key] = resolved_isa["datatypes"][dt][key].format(lmul=lmul)
            if "{eew_emul}" in resolved_isa["datatypes"][dt][key]:
                n_bits = datatypes[dt]["n_bits"]
                eew_emul = 0
                if int(lmul) == 0:
                    eew_emul = 1
                else :
                    eew_emul = str(int(int(n_bits)/int(lmul)))
                    #print(n_bits, lmul, eew_emul)
                resolved_isa["datatypes"][dt][key] = resolved_isa["datatypes"][dt][key].format(eew_emul=eew_emul)
    return resolved_isa

def gen_mipp_rvv(include_manager, vlen="__riscv_v_fixed_vlen"):
    #for iemu in implems_emu_rvv:
    #	for sub_iemu in implems_emu_rvv[iemu]:
    #		if "type" not in sub_iemu:
    #			sub_iemu["type"] = "emulated"
    # implementation C
    file_common = include_manager.get_fd(isa_rvv["name"], "common")
    if file_common is None:
        print("Panic: common.h file descriptor not found for RVV.")
        exit(-1)

    tpl_header_rvv = """#ifndef MY_INTRINSICS_PLUS_PLUS_IMPL_GEN_RVV_H_
#define MY_INTRINSICS_PLUS_PLUS_IMPL_GEN_RVV_H_
#include <riscv_vector.h>
#include <string.h>
#include <float.h>
#include <stdint.h>
#include <stdio.h>//remove after debug
#include <stdlib.h>//remove after debug
#define MIPP_RVV_VLEN {{vlen}}
typedef float float32_t;//remove after debug
typedef double float64_t;//remove after debug"""
    j2_template = Template(tpl_header_rvv, undefined=StrictUndefined)
    print(j2_template.render(vlen=vlen), file=file_common)

    ref_isa_name = isa_rvv["name"]
    #for function prototypes that use arrays declared w macros like MIPP_RVV256_N_FLOAT64 
    #we want the name to contain size. This is optional atm 
    #but if we want smtg similar to sve it will become useful
    isa_rvv["name"] = ref_isa_name #+str(vl) # Adrien: I commented "+str(vl)" because I use this field to generate "#if define(MIPP_RVV)" in the interfaces
    gen_c_defines_rvv_ls(file_common,ref_isa_name,vlen)
    gen_c_structures_rvv_ls(file_common,vlen)
    
    
    tpl_footer_rvv = """#endif /* MY_INTRINSICS_PLUS_PLUS_IMPL_GEN_RVV_H_ */"""
    j2_template = Template(tpl_footer_rvv, undefined=StrictUndefined)
    print(j2_template.render(), file=file_common)
    
    
    
    print("Generate RVV")
    copy_mipp_funcs = copy.deepcopy(mipp_funcs)
        
    isa_rvv_lmul1 = resolve_lmul_in_isa(isa_rvv, "1")
    
    for lmul in [0] + all_lmul:
        resolved_isa = resolve_lmul_in_isa(isa_rvv, str(lmul))
        gen_c_functions_rvv(resolved_isa, include_manager, copy_mipp_funcs, implems_rvv, lmul=lmul)
        ret = fix_reductions(resolved_isa, isa_rvv_lmul1, copy_mipp_funcs, implems_emu_rvv, lmul)

        gen_c_functions_rvv(resolved_isa, include_manager, copy_mipp_funcs, implems_emu_rvv, lmul=lmul, reductions_fix=ret)
        
        #rvv doesn't have any "if" in implems rvv so we can get away with calling gen_c_functions rvv instead of a
        #separate gen_c_generic_functions_rvv FOR NOW.
        #change this line if this ever changes.
        gen_c_functions_rvv(resolved_isa, include_manager, copy_mipp_funcs, implems_generic_emu, lmul=lmul)
        
        gen_c_functions_rvv(resolved_isa, include_manager, copy_mipp_funcs, implems_mask_generic_emu, lmul=lmul)

        gen_c_missing_functions_lmul(resolved_isa, include_manager, copy_mipp_funcs, lmul=lmul)
    
    #now that dependencies are resolved and functions are generated we can generate the headers for the functions with the correct includes
    #resolve all deps 
    
    include_manager.resolve_all_dependencies(isa_rvv["name"], copy_mipp_funcs)
    include_manager.create_glue_file(isa_rvv["name"], "../include/rvv/mipp_impl_rvv_gen.h")



    #file.close()